# Generated by Django 6.0.6 on 2026-06-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_seed_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': '✍ Blog Article', 'verbose_name_plural': '✍ Blog Articles'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': '✉ Email Message', 'verbose_name_plural': '✉ Email Messages'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': '🎓 Education Detail', 'verbose_name_plural': '🎓 Education Details'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': '💼 Work Experience', 'verbose_name_plural': '💼 Work Experiences'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '📁 Featured Project', 'verbose_name_plural': '📁 Featured Projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': '⚡ Technical Skill', 'verbose_name_plural': '⚡ Technical Skills'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name': '🏷 Skill Category', 'verbose_name_plural': '🏷 Skill Categories'},
        ),
        migrations.AlterModelOptions(
            name='typedrole',
            options={'verbose_name': '🎭 Typed Role', 'verbose_name_plural': '🎭 Typed Roles'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': '🤝 Meeting Request', 'verbose_name_plural': '🤝 Meeting Requests'},
        ),
    ]
