# Generated by Django 6.0.6 on 2026-06-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_blogpost_options_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sahil Thakur', max_length=150)),
                ('location', models.CharField(default='Ambala City, Haryana, India', max_length=200)),
                ('current_company', models.CharField(default='Crescaler R&D', max_length=200)),
                ('short_intro', models.TextField(default='Backend & AI Engineer skilled in Python, Django, FastAPI, PostgreSQL, Redis, Docker, and Agentic AI.')),
                ('email', models.EmailField(default='sahilrajput5321@gmail.com', max_length=254)),
                ('linkedin_url', models.URLField(default='https://linkedin.com')),
                ('github_url', models.URLField(default='https://github.com')),
                ('portfolio_url', models.URLField(default='https://sahilthakur.dev')),
                ('terminal_title', models.CharField(default='profile.py', max_length=100)),
                ('class_name', models.CharField(default='SahilThakur', max_length=100)),
                ('role', models.CharField(default='Backend & AI Engineer', max_length=150)),
                ('tech_stack', models.CharField(default='Python, FastAPI, Django, PostgreSQL, Docker, Redis', help_text='Comma-separated list of technologies', max_length=255)),
                ('ai_expertise', models.CharField(default='LangChain, CrewAI, Agentic AI, RAG, LLM Integration, Prompt Engineering, n8n', help_text='Comma-separated list of AI skills', max_length=255)),
                ('open_to_work', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Info',
                'verbose_name_plural': 'Hero Info',
            },
        ),
    ]
