# Generated by Django 6.0.6 on 2026-06-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_heroinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroinfo',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your Resume/CV PDF', null=True, upload_to='resumes/'),
        ),
    ]
