# Generated by Django 6.0.6 on 2026-06-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_heroinfo_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroinfo',
            name='about_me',
            field=models.TextField(default='Backend & AI Engineer skilled in Python, Django, FastAPI, PostgreSQL, Redis, Docker, and Agentic AI. Experienced in building scalable APIs, automation systems, RAG applications, and AI-powered solutions. Strong focus on backend architecture, performance optimization, and production-ready software development.'),
        ),
        migrations.AddField(
            model_name='heroinfo',
            name='ai_agents_built',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='heroinfo',
            name='contact_description',
            field=models.TextField(default="Open to full-time roles, freelance projects, and AI collaboration. Backend engineer ready to ship production-grade software. Reach out and let's talk."),
        ),
        migrations.AddField(
            model_name='heroinfo',
            name='experience_years',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='heroinfo',
            name='phone',
            field=models.CharField(default='+91 7404304607', max_length=50),
        ),
        migrations.AddField(
            model_name='heroinfo',
            name='projects_completed',
            field=models.IntegerField(default=10),
        ),
    ]
