# Generated by Django 6.0.6 on 2026-06-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_heroinfo_about_me_heroinfo_ai_agents_built_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Email, Phone, WhatsApp', max_length=100)),
                ('value', models.CharField(help_text='e.g. sahilrajput5321@gmail.com, +91 7404304607', max_length=255)),
                ('link', models.CharField(help_text='e.g. mailto:email, tel:phone, https://...', max_length=255)),
                ('icon_class', models.CharField(choices=[('fa-solid fa-envelope', 'Email'), ('fa-solid fa-phone', 'Phone'), ('fa-brands fa-whatsapp', 'WhatsApp'), ('fa-brands fa-linkedin', 'LinkedIn'), ('fa-brands fa-github', 'GitHub'), ('fa-solid fa-link', 'Website')], default='fa-solid fa-link', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Contact Method',
                'verbose_name_plural': 'Contact Methods',
                'ordering': ('order',),
            },
        ),
    ]
