# Generated by Django 6.0.6 on 2026-06-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_seed_contact_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmethod',
            name='is_full_width',
            field=models.BooleanField(default=False, help_text='Display as full width (100%) instead of half width (50%)'),
        ),
    ]
