# Generated by Django 6.0.6 on 2026-07-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_blogpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="author",
            field=models.CharField(blank=True, default="AI", max_length=100),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="source",
            field=models.CharField(blank=True, default="telegram", max_length=100),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
