# Generated by Django 6.0.6 on 2026-07-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0012_blogpost_author_blogpost_image_url_blogpost_source_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Draft", "Draft"), ("Published", "Published")],
                max_length=10,
                null=True,
            ),
        ),
    ]
