# Generated by Django 6.0.6 on 2026-07-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_alter_blogpost_author_alter_blogpost_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="card_image",
            field=models.ImageField(
                blank=True,
                help_text="Card thumbnail image file",
                null=True,
                upload_to="blog_images/cards/",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.CharField(
                blank=True, default="Technology", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="image_2",
            field=models.URLField(
                blank=True,
                help_text="Card thumbnail image URL",
                max_length=500,
                null=True,
            ),
        ),
    ]
