# Generated by Django 6.0.7 on 2026-07-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_blogpost_card_image_blogpost_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroinfo",
            name="brand_name",
            field=models.CharField(
                default="Sahil.dev",
                help_text="Brand text displayed in top navbar (e.g. Sahil.dev)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="heroinfo",
            name="logo_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload custom logo image for navbar",
                null=True,
                upload_to="logo/",
            ),
        ),
    ]
