# Generated by Django 6.0.7 on 2026-07-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_heroinfo_brand_name_heroinfo_logo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroinfo",
            name="brand_name",
            field=models.CharField(
                blank=True,
                help_text="Brand text displayed in top navbar (optional)",
                max_length=100,
                null=True,
            ),
        ),
    ]
