# Generated by Django 6.0.6 on 2026-07-26 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_alter_heroinfo_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="blog_post",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a Blog Article to explain this project in detail",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_projects",
                to="portfolio.blogpost",
                verbose_name="Linked Blog Article / Case Study",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="External URL or Github link (optional fallback if no blog article is linked)",
                null=True,
            ),
        ),
    ]
