# Generated by Django 6.0.6 on 2026-09-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_project_blog_post_alter_project_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="education_type",
            field=models.CharField(
                choices=[("Degree", "Degree"), ("School", "School")],
                default="Degree",
                help_text="Select Degree (College/University) or School (10th/12th)",
                max_length=20,
                verbose_name="Education Type",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(max_length=150, verbose_name="Degree / Class"),
        ),
    ]
