# Generated by Django 6.0.6 on 2026-09-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0018_education_education_type_alter_education_degree"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Workflow title (e.g. AI Customer Support Escalation Pipeline)",
                        max_length=180,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="n8n Automation",
                        help_text="Category/Type (e.g. n8n Automation, AI Agent, CRM Sync)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the workflow triggers, steps, and outcomes"
                    ),
                ),
                (
                    "technologies",
                    models.CharField(
                        help_text="Comma-separated tools/tech (e.g. n8n, OpenAI, Slack, Webhooks)",
                        max_length=255,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        default="fa-solid fa-diagram-project",
                        help_text="FontAwesome icon class",
                        max_length=100,
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="External URL, live demo, or GitHub repository",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=1, help_text="Display order sequence"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Automation Workflow",
                "verbose_name_plural": "Automation Workflows",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload workflow screenshot or diagram",
                        null=True,
                        upload_to="workflows/",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Or external image URL (e.g. Imgur, Cloudinary, AWS)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption (e.g. Node Execution Flow, Trigger Setup)",
                        max_length=200,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of this image within the workflow card",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.automationworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Image",
                "verbose_name_plural": "Workflow Images",
                "ordering": ["order", "id"],
            },
        ),
    ]
