from enum import Enum


class IntentType(str, Enum):
    GREETING = "greeting"
    LEARN_ABOUT = "learn_about"
    VIEW_PROJECTS = "view_projects"
    VIEW_EXPERIENCE = "view_experience"
    VIEW_RESUME = "view_resume"
    TECHNICAL_QUESTION = "technical_question"
    DISCUSS_INTERVIEW = "discuss_interview"
    SCHEDULE_INTERVIEW = "schedule_interview"
    DISCUSS_PROJECT = "discuss_project"
    UNDERSTAND_SERVICES = "understand_services"
    DISCUSS_PRICING = "discuss_pricing"
    SCHEDULE_CONSULTATION = "schedule_consultation"
    BECOME_LEAD = "become_lead"
    READ_BLOG = "read_blog"
    GENERAL_QUESTION = "general_question"
    MEETING_SCHEDULE = "meeting_schedule"
    MEETING_RESCHEDULE = "meeting_reschedule"
    MEETING_CANCEL = "meeting_cancel"
    GENERAL_CONVERSATION = "general_conversation"
    QUESTION_ANSWERING = "question_answering"
    LEAD_QUALIFICATION = "lead_qualification"
    REMINDER = "reminder"
    TASK_CREATION = "task_creation"
    INFORMATION_COLLECTION = "information_collection"
    WORKFLOW_TRIGGER = "workflow_trigger"
    FALLBACK = "fallback"
    UNKNOWN = "unknown"
