# Generated by Django 6.0.6 on 2026-06-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_emoji', models.CharField(max_length=10)),
                ('label', models.CharField(help_text='Display text', max_length=150)),
                ('url', models.URLField(help_text='Link URL (mailto:, tel:, https://...)')),
                ('full_width', models.BooleanField(default=False, help_text='Span full width of grid')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_emoji', models.CharField(default='🎓', max_length=10)),
                ('badge_text', models.CharField(help_text='e.g. Degree, Board Results', max_length=50)),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(help_text='e.g. Bachelor of Vocational (Software Development)', max_length=200)),
                ('date_range', models.CharField(help_text='e.g. Oct 2021 — Jul 2024', max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='e.g. Full Stack Developer — R&D Team', max_length=150)),
                ('start_date', models.CharField(help_text='e.g. 8/2025', max_length=30)),
                ('end_date', models.CharField(blank=True, default='Present', max_length=30)),
                ('is_current', models.BooleanField(default=False, help_text="Show green 'Present' badge")),
                ('intro_text', models.TextField(help_text='Short intro paragraph under the role')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name (e.g. Sahil Thakur)', max_length=100)),
                ('logo_text', models.CharField(default='ST', help_text='Short logo text for navbar', max_length=10)),
                ('location', models.CharField(help_text='City, State, Country', max_length=150)),
                ('eyebrow_text', models.CharField(default='Open to Opportunities', help_text='Small text above name in Hero', max_length=100)),
                ('hero_description', models.TextField(help_text='Short paragraph in Hero section')),
                ('summary_text', models.TextField(help_text='Longer summary paragraph in About section')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('resume_url', models.URLField(blank=True, help_text='Link to resume PDF')),
                ('terminal_role', models.CharField(default='Backend & AI Engineer', max_length=100)),
                ('terminal_company', models.CharField(default='Crescaler R&D', max_length=100)),
                ('terminal_stack', models.TextField(default='Python, FastAPI, Django, PostgreSQL, Docker, Redis', help_text='Comma-separated stack items for terminal card')),
                ('terminal_ai_expertise', models.TextField(default='LangChain, CrewAI, RAG, LLM Dev, Agentic AI, n8n', help_text='Comma-separated AI tools for terminal card')),
                ('contact_heading', models.CharField(default="Let's Build Something Great.", max_length=200)),
                ('contact_description', models.TextField(default="Open to full-time roles, freelance projects, and AI collaboration. Backend engineer ready to ship production-grade software. Reach out and let's talk.")),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('icon_emoji', models.CharField(default='🚀', max_length=10)),
                ('description', models.TextField()),
                ('project_url', models.URLField(blank=True, help_text='Link to live project or repo')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_emoji', models.CharField(default='💻', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. GitHub, LinkedIn', max_length=50)),
                ('url', models.URLField()),
                ('icon_svg', models.TextField(blank=True, help_text='SVG path markup for the icon (just the <path> d attribute or full <svg>)')),
                ('icon_emoji', models.CharField(blank=True, help_text='Fallback emoji if no SVG', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Target number for counter animation')),
                ('label', models.CharField(help_text='e.g. Client Projects', max_length=50)),
                ('show_plus', models.BooleanField(default=False, help_text='Show + after number (e.g. 10+)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TypedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Backend Engineer', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EducationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='home.education')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='home.experience')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='home.experience')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techs', to='home.experience')),
            ],
            options={
                'verbose_name': 'Experience Tech Tag',
                'verbose_name_plural': 'Experience Tech Tags',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techs', to='home.project')),
            ],
            options={
                'verbose_name': 'Project Tech Tag',
                'verbose_name_plural': 'Project Tech Tags',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home.skillcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
