# Generated by Django 6.0.6 on 2026-06-11 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short preview text (max 300 chars)', max_length=300)),
                ('content', models.TextField(help_text='Full blog content (supports HTML)')),
                ('cover_emoji', models.CharField(default='📝', help_text='Emoji icon for the blog card', max_length=10)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('published_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage (top 3 featured)')),
                ('is_published', models.BooleanField(default=True, help_text='Only published blogs are visible')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='home.blog')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
