# Generated by Django 6.0.6 on 2026-06-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_blogtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cover_emoji',
        ),
        migrations.RemoveField(
            model_name='contactitem',
            name='icon_emoji',
        ),
        migrations.RemoveField(
            model_name='education',
            name='badge_emoji',
        ),
        migrations.RemoveField(
            model_name='project',
            name='icon_emoji',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='icon_emoji',
        ),
        migrations.AddField(
            model_name='blog',
            name='cover_svg',
            field=models.TextField(blank=True, help_text='SVG icon for the blog card'),
        ),
        migrations.AddField(
            model_name='contactitem',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG for the contact icon'),
        ),
        migrations.AddField(
            model_name='education',
            name='badge_svg',
            field=models.TextField(blank=True, help_text='SVG for the badge icon'),
        ),
        migrations.AddField(
            model_name='profile',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Upload a logo image for the navbar', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG path or full tag for the project icon'),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG path or full tag for the icon'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='logo_text',
            field=models.CharField(default='ST', help_text='Short logo text for navbar (fallback)', max_length=10),
        ),
    ]
