# Generated by Django 6.0.6 on 2026-06-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_blog_cover_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the blog (replaces icon if provided)', null=True, upload_to='blog_covers/'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the project (replaces icon if provided)', null=True, upload_to='project_covers/'),
        ),
    ]
