# Generated by Django 6.0.6 on 2026-06-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog_cover_image_project_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='funnel_button_text',
            field=models.CharField(default='Start a Project', help_text='Text on the CTA button', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='funnel_button_url',
            field=models.CharField(default='#contact', help_text='URL or #id for the CTA button (e.g. mailto: or calendly link)', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='funnel_heading',
            field=models.CharField(default='Ready to build something amazing?', help_text='Main heading for the CTA', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='funnel_is_active',
            field=models.BooleanField(default=True, help_text='Show the marketing funnel CTA section'),
        ),
        migrations.AddField(
            model_name='profile',
            name='funnel_subheading',
            field=models.TextField(default="Let's turn your ideas into scalable, robust software.", help_text='Subheading for the CTA'),
        ),
    ]
