# Generated by Django 6.0.6 on 2026-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_funnel_button_text_profile_funnel_button_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('history', models.JSONField(blank=True, default=list, help_text='JSON serialized chat history')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
