# Generated by Django 6.0.6 on 2026-06-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_whatsappchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload resume PDF directly — AI will serve this link automatically', null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_url',
            field=models.URLField(blank=True, help_text='Link to resume PDF (external URL)'),
        ),
    ]
