# Generated by Django 6.0.6 on 2026-06-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile_resume_file_alter_profile_resume_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complexity_notes',
            field=models.TextField(blank=True, help_text='Describe challenges faced during this project — what was hard, what blocked you (AI will use this)'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_found',
            field=models.TextField(blank=True, help_text='Describe how you solved the challenges — your approach, tools used, breakthrough (AI will use this)'),
        ),
    ]
