# Generated by Django 6.0.6 on 2026-06-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_project_complexity_notes_project_solution_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_agent_intro',
            field=models.TextField(default='I can answer anything about Sahil — his experience, skills, projects, or how to get in touch.', help_text='Short introduction message for the AI Assistant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_agent_name',
            field=models.CharField(default='Daisy', help_text='Name of your AI Assistant', max_length=50),
        ),
    ]
