# Generated by Django 6.0.5 on 2026-05-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('recruiter', 'Recruiter'), ('scheduler', 'Sheduler'), ('portfolio', 'Portfolio')], max_length=50)),
                ('goal', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
