# Generated by Django 6.0.5 on 2026-06-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('research', 'Research'), ('portfolio', 'Portfolio'), ('client', 'Client'), ('project_explainer', 'Project Explainer'), ('recruiter', 'Recruiter')], max_length=50),
        ),
    ]
