# Generated by Django 6.0.5 on 2026-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_researchtask_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtask',
            name='agent_type',
            field=models.CharField(default='research', max_length=50),
        ),
    ]
