# Generated by Django 6.0.5 on 2026-06-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_researchtask_agent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
